bank_app/urls.py
from django.urls import path
from . import views
app_name='bank_app'

urlpatterns = [
    path('', views.index,name='index'),
    path('index', views.index,name='index'),
]

bank_proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank_app.urls')),
    path('credentials/',include('credentials.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

credentials/urls.py
from . import views
from django.urls import path

urlpatterns = [

    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('form1',views.form1,name='form1'),
    path('submit',views.submit,name='submit'),

]

bank_app/models.py
from django.db import models

# Create your models here.

credentials/models.py
from django.db import models

# Create your models here.

bank_app/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'index.html')

credentials/views.py
from django.contrib import messages,auth
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

# Create your views here.

def register(request):
    if request.method=='POST':
        username=request.POST['username']
        email=request.POST['email']
        password=request.POST['password']
        cpassword=request.POST['password1']
        if password==cpassword:
            if User.objects.filter (username=username).exists():
                messages.info(request,"Username Exists")
                print("Username already exists")
                return redirect('register')
            elif User.objects.filter (email=email).exists():
                messages.info(request,"Email Id Taken")
                return redirect('register')
            else:
                user=User.objects.create_user(username=username,email=email,password=password)
                user.save()
                print("User registraton successful !!!")
                return redirect('login')
        else:
            messages.info(request,"Passwords donot match.")
            return redirect('register')
        return redirect('/')
    return render(request,'register.html')


def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        
        if user is not None:
            auth.login(request,user)
            return render(request,'form_button.html')
        else:
            messages.info(request,"Invalid credentials")
    return render(request,"login.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

def form1(request):
    return render(request,'form.html')

def submit(request):
    messages.info(request,"User registration successful")
    return render(request,'form.html')

templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <link rel="stylesheet" href="{% static 'assets/css/my_custom.css' %}">
    <script>
        var subjectObject = {
          "Alappuzha": {
            "Ambalappuzha": [],
            "Chengannur": [],
            "Cherthala": [],
            "Karthikappally": [],
            "Kuttanad": []
          },
          "Ernakulam": {
            "Aluva": [],
            "Kochi": [],
            "Kothamangalam": [],
            "Muvattupuzha": [],
            "Paravur": []
          },
          "Idukki": {
            "Devikulam": [],
            "Kattappana": [],
            "Thodupuzha": [],
            "Peerumade": [],
            "Udumbanchola": []  
          },
          "Kannur": {
            "Iritty": [],
            "Kuthuparamba": [],
            "Payyannur": [],
            "Taliparamba": [],
            "Thalassery": []    
          },
          "Kasaragod": {
            "Hosdurg": [],
            "Kanhangad": [],
            "Manjeswaram": [],
            "Nileshwar": [],
            "Vellarikkundu": []
          },
          "Kollam": {
            "Pathanapuram": [],
            "Punalur": [],
            "Kunnathur": [],
            "Kottarakkara": [],
            "Karunagappally": []
          },
          "Kottayam": {
            "Changanassery": [],
            "Ettumanoor": [],
            "Kanjirappally": [],
            "Meenachil": [],
            "Vaikom": []
          },
          "Kozhikode": {
            "Koyilandi": [],
            "Thamarassery": [],
            "Vatakara": []
          },
          "Malappuram": {
            "Ernad": [],
            "Kondotty": [],
            "Nilambur": [],
            "Perinthalmanna": [],
            "Ponnani": [],
            "Tirur": []
          },
          "Palakkad": {
            "Alathur": [],
            "Chittur": [],
            "Mannarkad": [],
            "Ottappalam": [],
            "Pattambi": []
          },
          "Pathanamthitta": {
            "Adoor": [],
            "Konni": [],
            "Mallappally": [],
            "Ranni": [],
            "Thiruvalla": []
          },
          "Thiruvananthapuram": {
            "Chirayinkeezhu": [],
            "Neyyattinkara": [],
            "Varkala": [],
            "Nedumangadu": [],
            "Kattakada": []
          },
          "Thrissur": {
            "Chalakkudy": [],
            "Chavakkad": [],
            "Kodungallur": [],
            "Kunnamkulam": [],
            "Talappilly": [] 
          },
          "Wayanad": {
            "Mananthavady": [],
            "Sulthanbathery": [],
            "Vythiri": []
          },
        }
        window.onload = function() {
          var districtSel = document.getElementById("district");
          var branchSel = document.getElementById("branch");
          for (var x in subjectObject) {
            districtSel.options[districtSel.options.length] = new Option(x, x);
          }
          districtSel.onchange = function() {
            //empty Chapters- and Topics- dropdowns
            branchSel.length = 1;
            //display correct values
            for (var y in subjectObject[this.value]) {
              branchSel.options[branchSel.options.length] = new Option(y, y);
            }
          }
        }
        </script>
    <title>Form</title>
</head>
<body>
  <div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->
        <h2 class="active"> Registration Form </h2>
      <form action="submit" method="">
          {% csrf_token %}
          <label for="name">Name: </label>
          <input type="text" id="name" name="name" placeholder="Name" required><br><br>
          <label for="dob">Date of birth:</label>
          <input type="date" id="dob" name="dob" required><br><br>
          <label for="age">Age: </label>
          <input type="text" id="age" name="age" placeholder="Age" required><br><br>
          <label for=""> Gender:</label>
          <input type="radio" id="male" name="male" value="Male">
          <label for="male"> Male</label>
          <input type="radio" id="female" name="male" value="Female">
          <label for="female"> Female</label>
          <input type="radio" id="other" name="male" value="Other">
          <label for="other"> Other</label><br><br>
          <label for="phone">Enter your phone number:</label>
          <input type="tel" id="phone" name="phone" placeholder="1234-567-890" required><br><br>
          <label for="email">Enter your email:</label>
          <input type="email" id="email" name="email" placeholder="Email ID" required><br><br>
          <label for="address">Address: </label>
          <input type="text" id="address" name="address" placeholder="Address" required><br><br>
          Districts: <select name="district" id="district">
                  <option value="" selected="selected">Select a district</option></select><br><br>
          Branches: <select name="branch" id="branch">
              <option value="" selected="selected">Please select district first</option></select><br><br>
          <label for=""> Items provided:</label>
          <input type="checkbox" id="debit" name="debit" value="Debit">
          <label for="debit"> Debit Card</label>
          <input type="checkbox" id="credit" name="credit" value="Credit">
          <label for="credit"> Credit card</label>
          <input type="checkbox" id="cheque book" name="cheque book" value="Cheque bookt">
          <label for="cheque book"> Cheque</label><br><br>
          <input type="submit" value="Submit">
        </form>
        {% for msg in messages %}
              {{msg}}
        {% endfor %}
        <br>
        <form action="logout">
          <input type="submit" value="Logout">
        </form>
        <br>
        <a class="active" href="{% url 'bank_app:index' %}"> Home </a>
        <br><br>
    </div>
  </div>
</body>
</html>

templates/form_button.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
    <title>Button</title>
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <h2 class="active"> Button </h2>

            <!-- Login Form -->
            <form action="form1">
                <input type="submit" class="first" value="Go to Registration Form">
            </form>
            <br>
        </div>
        
    </div>

</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
    <title>Login</title>
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <h2 class="active"> Sign In </h2>
            <h2><a class="active" href="{% url 'bank_app:index' %}"> Home </a></h2>

            <!-- Login Form -->
            <form action="login" method="post">
                {% csrf_token %}
                <input type="text" class="fadeIn first" name="username" placeholder="Username">
                <input type="password" class="fadeIn second" name="password" placeholder="Password">
                <input type="submit" class="fadeIn third" value="Log In">
                <a class="fadeIn fourth" href="register">Don't have a account Register Here</a>
            </form>
            {% for msg in messages %}
            {{msg}}
            {% endfor %}
            <br>
        </div>
    </div>

</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
    <title>Register</title>
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <h2 class="active"> Sign Up </h2>
            <h2><a class="active" href="{% url 'bank_app:index' %}"> Home </a></h2>

            <!-- Login Form -->
            <form action="register" method="post">
                {% csrf_token %}
                <p><input type="text"class="fadeIn first" name="username" placeholder="Username" required></p>
                <p><input type="email" class="fadeIn second" name="email" placeholder="Email Id" required></p>
                <p><input type="password" class="fadeIn third" name="password" placeholder="Password" required></p>
                <p><input type="password" class="fadeIn fourth" name="password1" placeholder="Confirm Password" required></p>
                <input type="submit" class="fadeIn fifth" value="Sign Up">
                <a class="fadeIn sixth" href="login">Already have a account Login now</a>
            </form>
            {% for msg in messages %}
            {{msg}}
            {% endfor %}
            <br>
        </div>
    
</body>
</html>